appImage: gcr.io/google-samples/microservices-demo/servicename
appName: servicename
appReplicas: 1
appVersion: v0.0.0
containerEnvVars:
- name: ENV_VAR_ONE
  value: valueone
- name: ENV_VAR_TWO
  value: valuetwo
containerPort: 8080

servicePort: 8080
serviceType: ClusterIP

